### ISSUE TITLE
It is not possible to specify error type or subclass

### ISSUE THREAD

**Issue by aufflick** [JensRavens/Interstellar#11]
Hi,

I'm looking at using Interstellar for a nice simple signal type, but I want the .error() callback to be typed. There are two ways this could work, either the class is Signal<T,E> where E is the specific error class, or I thought without patching I could subclass specific eg:

```
class FooSignal : Signal<Foo> {
   public func error(g: FooError -> Void) -> signal ... etc
}
```

But the class is marked final. Is there any specific reason to disallow subclassing?

**Comment by JensRavens** [comment]
Error handling is implicit because it is implicit in Swift (in regards to throwing functions). As signals support throwing functions it's not possible to strongly type them. If you want to route a specific error you can still cast it in the subscribe function or use an ensure-method to redirect them.

**Comment by JensRavens** [comment]
For the subclassing part: Swift used to be [faster for final classes](http://blog.human-friendly.com/the-importance-of-being-final). Although this is not the case anymore, I still don't see a point in subclassing `Signal`. It's meant to be a base type like `Int` or `Array<T>` which are almost never a good idea to subclass.

**Comment by JensRavens** [comment]
In V2 you can bring your own result type, therefore also use your own error type.
