### ISSUE TITLE
Signal could be struct

### ISSUE THREAD

**Issue by sashankg** [JensRavens/Interstellar#21]
Wouldn't it be better to have the Signal object be a struct rather than a final class. This is ensures safety when copying and is preferred in Swift (as seen in [this talk](https://www.youtube.com/watch?v=g2LwFZatfTI)) over classes. Really, I just wanted to know why it was a final class.

**Comment by JensRavens** [comment]
Signals have to be classes so they can be referenced (classes are reference types, structs are not).

``` swift
let a = Signal<String>()

func doSomething(s: Signal<String>) {
  s.next { string in
    // do something important
 }
}

doSomething(a)
a.update("Hello")
```

If Signal would be a value type, `doSomething` wouldn't be able to change it (it could declare `s` as `inout mutable`, but that just breaks the whole concept of sane dependencies). Therefore the signal couldn't add the func as a subscriber and also it cannot call it back. `s` would never update and call their subscribers, because it would be a different instance than `a`.

So no, signal could not be a struct.

**Comment by sashankg** [comment]
Thanks!
