### ISSUE TITLE
Zero-Knowledge Disposal

### ISSUE THREAD

**Issue by Mazyod** [JensRavens/Interstellar#70]
Thanks for publishing this great library!

I really loved it, but I quickly faced a problem (for me at least). I am trying to implement a "service-oriented architecture", which is basically just a bunch of services that are instantiated then bound together through observables to make the whole thing "tick". They should not know about each other, except for the `Observable` being passed in from the binding object. Doing this makes it impossible to clean up the observer, since `unsubscribe` requires access to the `Observable`.

Pondering on this a bit, I thought of this, and would like to hear your thoughts about it. It could use a bit of type-erasure, and other tune ups, but was wondering if you're interested in this direction:

```swift
final class Subscription<T> {

    private weak var observable: Observable<T>?
    private let token: ObserverToken

    init(observable: Observable<T>, token: ObserverToken) {
        self.observable = observable
        self.token = token
    }

    deinit {
        observable?.unsubscribe(token)
    }
}

extension ObserverToken {

    func subscription<T>(from observable: Observable<T>) -> Subscription<T> {
        return Subscription(observable: observable, token: self)
    }
}
```

**Comment by Mazyod** [comment]
Type-erased version:

```swift
protocol AnyObservable: class {

    func unsubscribe(_ token: ObserverToken)
}

extension Observable: AnyObservable {

}

final class Subscription {

    private weak var observable: AnyObservable?
    private let token: ObserverToken

    init(observable: AnyObservable, token: ObserverToken) {
        self.observable = observable
        self.token = token
    }

    deinit {
        observable?.unsubscribe(token)
    }
}

extension ObserverToken {

    func subscription<T>(from observable: Observable<T>) -> Subscription {
        return Subscription(observable: observable, token: self)
    }
}

```

**Comment by JensRavens** [comment]
If I get it correctly you're implementing something that the library does anyway: Once an observable is dropped from memory, it releases all its observing functions (and other things that are retained by those). Calling unsubscribe is therefore not actually needed in almost all cases (so far I never used it myself, it was just integrated into the library because so many people asked for it - but basically you should never need it).

**Comment by Mazyod** [comment]
Thanks for the explanation, @JensRavens. You're right, and I am not worried about the `Observable` being dropped from memory, nor about the `Observer` being dropped either (since I can capture weakly in the observation closure).

The problem I'm trying to solve is what if you want to bind, then re-bind objects without them ever being deallocated? Take a `UITableViewCell` as an example, since it's reused, and never deallocated.

```swift
final class Cell: UITableViewCell {

  func bind(observable: Observable<String>) {
    // Uh-oh .. need to unsubscribe from previous observable
    // I need to retain the observables somehow then...
    self.weakObservable.unsubscribe(self.token)
    self.weakObservable = observable
    self.token = observable.subscribe(...)
  }
}
```

You see how this burden of maintaining two properties, and doing the unsubscribed dance would be required in this case, since both objects are still in-memory?

**Comment by JensRavens** [comment]
Yes, this is the usecase that is handled by dispose-bags in other frameworks. I don't want to introduce this complicated concept into the library, that's why I'm looking for other ways. 

Maybe it would make sense to change the implementation of `ObserverToken`. It was implemented in the first place as an opaque thing to store until we come up with a better implementation. Maybe it's time to change it to a struct now and implement the `unsubscribe` function directly on it.

**Comment by Mazyod** [comment]
@JensRavens I'm happy to raise a PR with that idea in mind if you're busy. I presume the only additional change would be to retain the observable weakly within the token for the unsubscribe to work without the need to pass in any additional parameter.
